In [27]:
# import the modules
import numpy as np

# define the inputs
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

layers = [2, 2, 1]

W = []

In [28]:
# initializing weights for the initial layers
for i in range(0, len(layers) - 2):
    W.append(np.random.randn(layers[i] + 1, layers[i+1] + 1) / np.sqrt(layers[i]))
print(W)

[array([[-0.69720651, -0.92577273, -0.96861831],
       [-0.57432443, -0.05792479, -1.50461605],
       [-0.11930924, -0.63296105, -0.13514875]])]


In [29]:
# initializing weights for the last layer
W.append(np.random.randn(layers[-2] + 1, layers[-1]) / np.sqrt(layers[-2]))
for i in W:
    print("-------------")
    print(i)

-------------
[[-0.69720651 -0.92577273 -0.96861831]
 [-0.57432443 -0.05792479 -1.50461605]
 [-0.11930924 -0.63296105 -0.13514875]]
-------------
[[-0.38512008]
 [-0.82929129]
 [ 0.06491673]]


In [30]:
# bias trick for X
X = np.c_[X, np.ones(X.shape[0])]
print(X)

[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [31]:
def sigmoid(x):
    return 1.0/(1 + np.exp(-x))

In [39]:
def sigmoid_deriv(x):
    return x * (1 - x)

In [36]:
for (x, target) in zip(X, y):
    A = [np.atleast_2d(x)]

    # feedforward
    for i in range(0, len(W)):
        net = np.dot(A[i], W[i])

        out = sigmoid(net)
        A.append(out)

    print("[INFO] Values in A:")
    for i in A:
        print("-------------")
        print(i)
    
    # backpropagation
    error = A[-1] - y
    
    D = [error * sigmoid_deriv(A[-1])]
    

-------------
[[0. 0. 1.]]
-------------
[[0.47020802 0.34683943 0.46626415]]
-------------
[[0.39211057]]
-------------
[[0. 1. 1.]]
-------------
[[0.33322523 0.33383604 0.16249707]]
-------------
[[0.40260316]]
-------------
[[1. 0. 1.]]
-------------
[[0.30650377 0.17382842 0.24903473]]
-------------
[[0.43880123]]
-------------
[[1. 1. 1.]]
-------------
[[0.19927366 0.16566621 0.06860084]]
-------------
[[0.44777208]]
